server:
  port: 7002
eureka:
  instance:
    hostname: server2
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://server1:7001/eureka/,http://server3:7003/eureka/
