server:
  port: 7001
eureka:
  instance:
    hostname: server1
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://server2:7002/eureka/,http://server3:7003/eureka/
