server:
  port: 7003
eureka:
  instance:
    hostname: server3
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://server2:7002/eureka/,http://server1:7001/eureka/
