server:
  port: 8083
mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
  type-aliases-package: com.lxl.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  application:
    name: springcloud-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db_03?useUnicode=true&characterEncoding=utf-8
    username: root
    password: liuxiaolie
logging:
  level:
    com.lxl.dao: debug
eureka:
  client:
    service-url:
      defaultZone: http://server1:7001/eureka/,ttp://server2:7002/eureka/,http://server3:7003/eureka/
  instance:
    instance-id: springcloud-provider-8083
info:
  app.name: springCloud-provider
